### ISSUE TITLE
Documentation mistakes

### ISSUE THREAD

**Issue by Funtime60** [LouisB3/KSP-ExtendedAntennaProgression#1]
I'm not sure if this is the right place or if anyone cares, but on the front page there is an error with the units. All the antennas are listed with a range of so many gigameters or terameters. However, while you likely know this, the power rating is not static like I think it was in remote tech. The configs give the DSN lv.6 a power of 31.25 T not Tm as there is no distance involved in the unit. I also recommend a calculator like [this ](https://docs.google.com/spreadsheets/d/1qIgFB8OXnlgpPCGsxv7JYUYQq5O671IcZXpumVaStek/edit#gid=1781472150) for the wiki page. Thanks for taking the time to read this and sorry if it was unnecessary, unwanted, and/or I don't respond to any responses. I'm not very active here.

Thank you

**Comment by LouisB3** [comment]
I am addressing this by making the documentation less verbose, as part of an overall effort to simplify this mod's offerings.
